@startmindmap
<style>
mindmapDiagram {
  .aggregate {
    BackgroundColor #ffd42d
  }
  .action {
    BackgroundColor #3399fe
  }
  .event {
    BackgroundColor #ff992a
  }
  .view {
    BackgroundColor #5fc08b
  }
  .business_process {
    BackgroundColor pink
  }
}
</style>
+ Customer <<aggregate>>
-- RegisterCustomer <<action>>
++ IdentityVerification <<business_process>>
+++ CustomerAdded <<event>>
+++ CustomerRejected <<event>>
+ Card <<aggregate>>
-- AddCard <<action>>
++ CreditCheck <<business_process>>
+++ CardAdded <<event>>
+ Payments <<aggregate>>
-- MakeCardPayment <<action>>
++ CardPayed <<event>>
+ Offers <<aggregate>>
-- CardPayed <<event>>
++ SendCardUpgradeOffer <<action>>
+ Purchases <<aggregate>>
-- MakeCardPurchase <<action>>
++ ValidateTransaction <<business_process>>
+++ CardPurchaseMade <<event>>
+++ CardPurchaseDenied <<event>>
+ Offers <<aggregate>>
-- CardPurchaseMade <<event>>
++ SendAffiliatedItemsOffer <<action>>
@endmindmap
